# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 797)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(290, 710, 113, 32))
        self.updateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateButton.setObjectName("updateButton")
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setGeometry(QtCore.QRect(20, 620, 651, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.divider.setFont(font)
        self.divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider.setObjectName("divider")
        self.MeanFilterButton = QtWidgets.QPushButton(self.centralwidget)
        self.MeanFilterButton.setEnabled(False)
        self.MeanFilterButton.setGeometry(QtCore.QRect(20, 640, 113, 32))
        self.MeanFilterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MeanFilterButton.setObjectName("MeanFilterButton")
        self.filenameLabel = QtWidgets.QLabel(self.centralwidget)
        self.filenameLabel.setGeometry(QtCore.QRect(50, 10, 591, 20))
        self.filenameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filenameLabel.setObjectName("filenameLabel")
        self.VideoSlider = QtWidgets.QSlider(self.centralwidget)
        self.VideoSlider.setEnabled(False)
        self.VideoSlider.setGeometry(QtCore.QRect(10, 550, 561, 22))
        self.VideoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VideoSlider.setObjectName("VideoSlider")
        self.singleLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.singleLeftButton.setGeometry(QtCore.QRect(60, 570, 51, 31))
        self.singleLeftButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.singleLeftButton.setObjectName("singleLeftButton")
        self.doubleLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.doubleLeftButton.setGeometry(QtCore.QRect(10, 570, 51, 31))
        self.doubleLeftButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleLeftButton.setObjectName("doubleLeftButton")
        self.singleRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.singleRightButton.setGeometry(QtCore.QRect(110, 570, 51, 31))
        self.singleRightButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.singleRightButton.setObjectName("singleRightButton")
        self.doubleRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.doubleRightButton.setGeometry(QtCore.QRect(160, 570, 51, 31))
        self.doubleRightButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleRightButton.setObjectName("doubleRightButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 671, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.videoGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.videoGridLayout.setContentsMargins(0, 0, 0, 0)
        self.videoGridLayout.setObjectName("videoGridLayout")
        self.frameLabel = QtWidgets.QLabel(self.centralwidget)
        self.frameLabel.setGeometry(QtCore.QRect(590, 554, 71, 16))
        self.frameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameLabel.setObjectName("frameLabel")
        self.accuracyLabel = QtWidgets.QLabel(self.centralwidget)
        self.accuracyLabel.setGeometry(QtCore.QRect(550, 570, 60, 16))
        self.accuracyLabel.setObjectName("accuracyLabel")
        self.percentageLabel = QtWidgets.QLabel(self.centralwidget)
        self.percentageLabel.setGeometry(QtCore.QRect(620, 570, 60, 16))
        self.percentageLabel.setObjectName("percentageLabel")
        self.FrameZeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.FrameZeroButton.setGeometry(QtCore.QRect(250, 666, 113, 32))
        self.FrameZeroButton.setObjectName("FrameZeroButton")
        self.startLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startLineEdit.setGeometry(QtCore.QRect(30, 670, 91, 21))
        self.startLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.startLineEdit.setObjectName("startLineEdit")
        self.dashedLabel = QtWidgets.QLabel(self.centralwidget)
        self.dashedLabel.setGeometry(QtCore.QRect(130, 670, 16, 16))
        self.dashedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dashedLabel.setObjectName("dashedLabel")
        self.stopLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.stopLineEdit.setGeometry(QtCore.QRect(150, 670, 91, 21))
        self.stopLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stopLineEdit.setObjectName("stopLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.MeanFilterButton.setText(_translate("MainWindow", "Mean Filter"))
        self.filenameLabel.setText(_translate("MainWindow", "Filename"))
        self.singleLeftButton.setText(_translate("MainWindow", "<"))
        self.doubleLeftButton.setText(_translate("MainWindow", "<<"))
        self.singleRightButton.setText(_translate("MainWindow", ">"))
        self.doubleRightButton.setText(_translate("MainWindow", ">>"))
        self.frameLabel.setText(_translate("MainWindow", "0/0"))
        self.accuracyLabel.setText(_translate("MainWindow", "Accuracy:"))
        self.percentageLabel.setText(_translate("MainWindow", "0%"))
        self.FrameZeroButton.setText(_translate("MainWindow", "Frame to Zero"))
        self.dashedLabel.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
